version: '3.7'
services:
  nu-site-parser:
    build: ./
    hostname: nu-site-parser
    volumes:
      - ./app:/app:z
    restart: always
    ports:
      - "8282:8282"
    networks:
      - intservices

  revers-proxy:
    image: nginx:latest
    hostname: revers-proxy
    volumes:
      - ./nginx:/etc/nginx/:z
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - intservices

networks:
  intservices:
    name: net-intservices
    driver: bridge